import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
print("..............")
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
print("..............")
zeros = np.zeros(5)
print(zeros)
print("..............")
ones = np.ones((2, 3))
print(ones)
print("..............")
identity_matrix = np.eye(3)
print(identity_matrix)
print("..............")
range_array = np.arange(0, 10, 2)
print(range_array)
print("..............")